name: Deploy WordPress Content causing FTP

on:
  push:
    branches:
      - main
    paths:
      - 'app/public/wp-content/themes/**'
      - 'app/public/wp-content/plugins/**'
      - 'app/public/wp-content/mu-plugins/**'

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync WP Content
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./app/public/wp-content/
          server-dir: ./public_html/wp-content/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/uploads/**
            **/cache/**
            **/.DS_Store
